living_room_ceiling:
  name: Living Room Ceiling
  entities:
    - light.living_room_ceiling_1a
    - light.living_room_ceiling_1b
    - light.living_room_ceiling_1c

living_room:
  name: Living Room
  entities:
    - group.living_room_ceiling
    - light.study_lamp
    - media_player.living_room_speaker
    - switch.projector

bedroom:
  name: Bedroom
  entities:
    - light.bedroom_lamp

bathroom:
  name: Bathroom
  entities:
    - light.bathroom_ceiling

common:
  name: Common
  entities:
    - light.cooler
