- platform: broadlink
  host: 192.168.178.29
  mac: 78:0F:77:5A:B1:B3
  type: rm_mini
  switches:
    projector:
      command_on: 'JgBQAAABKZUUERU1FREUERU1FTYVEBURFDYVEBU2FTUVERQRFTUVNhUQFTYVEBUQFREUERUQFRAVNhUQFTYVNRU2FDYVNhU1FQAFCgABK0kVAA0FAAAAAAAAAAA='
      command_off: 'JgBYAAABKZQTExM3ExITExM3EzgTEhMSFDcUERQ3FDYUERQSFDYUNxUQFTUWNRU1FhAVNRURFRAVNRURFRAVEBU2FRAVNRY1FQAFCQABLEgVAAxQAAErSBUADQU='
